force-app/main/default/objects/Accounts_with_Unified_Details__c/Accounts_with_Unified_Details__c.object-meta.xml
<CustomObject>
    <label>Accounts with Unified Details</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts with Unified Detailss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculated_Insight__c/Calculated_Insight__c.object-meta.xml
<CustomObject>
    <label>Calculated Insight</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calculated Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insight_Field__c/Insight_Field__c.object-meta.xml
<CustomObject>
    <label>Insight Field</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insight Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insight_Field__c/fields/Calculated_Insight__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Insight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Calculated Insight</label>
    <referenceTo>Calculated_Insight__c</referenceTo>
    <relationshipLabel>Insight Fields</relationshipLabel>
    <relationshipName>Insight_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/manualTestSmartSyncUtility.cls
public class manualTestSmartSyncUtility {
	public static void cleanDataForMeta()
    {
        Insight_Field__c[] lstFields = [SELECT Id FROM Insight_Field__c];
        if(lstFields.size()>0)
            delete lstFields;
        Calculated_Insight__c[] lstCi=[SELECT Id FROM Calculated_Insight__c];
        if(lstCi.size()>0)
            delete lstCi;  
        
    }
    /*
     ////////*********Start Calling Your Methods ************////
//manualTestSmartSyncUtility.cleanDataForMeta();//for Objects with CI metadata
//Run script to clear data for ciMimic object //cant keep here as then u ll not b able to del the object
//SmartSyncInitializer.createCiMetaSnapshots();
//SmartSyncInitializer.getSelectedCI('Accounts_with_Unified_Details');
//PermissionSetUpdater.grantCrudAccessViaMetadata('Accounts_with_Unified_Details__c','SmartSyncConsole','SmartSyncConsole');
//PermissionSetUpdater.grantFullAccessToPermissionSet('Accounts_with_Unified_Details__c','SmartSyncConsole'); //worked for Fields 
//SmartSyncInitializer.getDataOfSelectedCI('Accounts_with_Unified_Details',false);
/********End of Test script *********************///

    /*check FLS amendment to PS from backened 
        SELECT Id, SObjectType, Field, PermissionsRead, PermissionsEdit, ParentId
        FROM FieldPermissions
        WHERE SObjectType = 'Accounts_with_Unified_Details__c'
        AND Parent.Name = 'SmartSyncConsole'
    */
    /*Check Object CRUD accesses from backened
        SELECT Id,Parent.Name,PermissionsCreate,PermissionsDelete,PermissionsEdit,PermissionsModifyAllRecords,SobjectType
        FROM ObjectPermissions 
        WHERE SObjectType = 'Accounts_with_Unified_Details__c'
     
     */
}